#ifndef TEST_GAME_H
#define TEST_GAME_H

#include <stdbool.h>

bool test_is_starved_opponent_player_one_should_return_true(void);
bool test_is_starved_opponent_player_one_should_return_false(void);
bool test_is_starved_opponent_player_two_should_return_true(void);
bool test_is_starved_opponent_player_two_should_return_false(void);
bool test_exists_move_that_feeds_opponent_player_one_should_return_true(void);
bool test_exists_move_that_feeds_opponent_player_one_should_return_false(void);
bool test_exists_move_that_feeds_opponent_player_two_should_return_true(void);
bool test_exists_move_that_feeds_opponent_player_two_should_return_false(void);
bool test_is_opponent_hole_player_one_should_return_true(void);
bool test_is_opponent_hole_player_one_should_return_false(void);
bool test_is_opponent_hole_player_two_should_return_true(void);
bool test_is_opponent_hole_player_two_should_return_false(void);
bool test_is_starved_self_player_one_should_return_true(void);
bool test_is_starved_self_player_one_should_return_false(void);
bool test_is_starved_self_player_two_should_return_true(void);
bool test_is_starved_self_player_two_should_return_false(void);
bool test_opponent_captures_its_balls_player_one(void);
bool test_opponent_captures_its_balls_player_two(void);

#endif
